"""Venue page generation tests (CLAUDE.md §9 Task 8).

Validates that:

  - ``scripts/generate_venue_pages.py`` emits one Markdown file per AGV.
  - Each page wires in the expected component imports and data loaders.
  - Each page's ``title`` frontmatter matches the canonical ``name_en``.
  - Regeneration is byte-deterministic (``--check`` passes on clean tree).
  - ``verificationBadge.js`` and ``evidencePanel.js`` exist with expected exports.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_AGV = REPO_ROOT / "data" / "agv.csv"
VENUES_DIR = REPO_ROOT / "src" / "venues"
COMPONENTS_DIR = REPO_ROOT / "src" / "components"
GENERATOR = REPO_ROOT / "scripts" / "generate_venue_pages.py"


def _load_agv_ids() -> list[str]:
    import csv
    with DATA_AGV.open(newline="", encoding="utf-8") as f:
        return [r["agv_id"] for r in csv.DictReader(f)]


def _load_agv_rows() -> list[dict]:
    import csv
    with DATA_AGV.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


AGV_IDS = _load_agv_ids()


# ---- file presence ----

def test_one_page_per_agv():
    agv_ids = set(AGV_IDS)
    pages = {p.stem for p in VENUES_DIR.glob("*.md") if p.name != "index.md"}
    missing = agv_ids - pages
    orphan = pages - agv_ids
    assert not missing, f"missing venue pages: {sorted(missing)[:5]}"
    assert not orphan, f"orphan venue pages (no matching agv_id): {sorted(orphan)[:5]}"


def test_venues_index_exists():
    assert (VENUES_DIR / "index.md").exists()


def test_components_exist():
    assert (COMPONENTS_DIR / "verificationBadge.js").exists()
    assert (COMPONENTS_DIR / "evidencePanel.js").exists()


def test_components_export_expected_functions():
    vb = (COMPONENTS_DIR / "verificationBadge.js").read_text(encoding="utf-8")
    assert "export function verificationBadge" in vb
    ep = (COMPONENTS_DIR / "evidencePanel.js").read_text(encoding="utf-8")
    assert "export function evidencePanel" in ep


# ---- per-page shape ----

@pytest.mark.parametrize("row", _load_agv_rows()[:10], ids=lambda r: r["agv_id"])
def test_page_has_auto_generated_marker_and_required_imports(row):
    """Sample-check 10 pages; the generator is deterministic so this is
    representative."""
    page = VENUES_DIR / f"{row['agv_id']}.md"
    body = page.read_text(encoding="utf-8")
    assert "Auto-generated by scripts/generate_venue_pages.py" in body
    # Title matches name_en (escaped for YAML)
    name_en_escaped = row["name_en"].replace("\\", "\\\\").replace('"', '\\"')
    assert f'title: "{name_en_escaped}"' in body, page
    # Verification badge call
    assert "${verificationBadge(agv, evidence)}" in body
    # Evidence panel call
    assert "${evidencePanel(evidence)}" in body
    # Component imports
    assert (
        'import {verificationBadge} from "../components/verificationBadge.js"'
        in body
    )
    assert (
        'import {evidencePanel} from "../components/evidencePanel.js"'
        in body
    )
    # Data loader references
    assert 'FileAttachment("../data/agv.json")' in body
    assert 'FileAttachment("../data/evidence.json")' in body
    assert 'FileAttachment("../data/lifecycle.json")' in body
    assert 'FileAttachment("../data/name_history.json")' in body
    # agvId matches
    assert f'const agvId = "{row["agv_id"]}";' in body


def test_all_pages_are_nonempty():
    for aid in AGV_IDS:
        page = VENUES_DIR / f"{aid}.md"
        assert page.exists(), aid
        assert page.stat().st_size > 500, aid


def test_all_pages_reference_their_own_agv_id():
    for aid in AGV_IDS:
        body = (VENUES_DIR / f"{aid}.md").read_text(encoding="utf-8")
        assert f'const agvId = "{aid}";' in body, aid


def test_all_pages_declare_all_six_ontology_fields():
    required = [
        "entity_type",
        "governance_modality_primary",
        "topic_focus_primary",
        "geographic_scope",
        "lead_actor_primary",
        "legal_character",
    ]
    # Pick a random-ish subset to keep test-time low
    for aid in AGV_IDS[::15]:
        body = (VENUES_DIR / f"{aid}.md").read_text(encoding="utf-8")
        for f in required:
            assert f"**{f}**" in body, f"{aid}: missing field {f}"


# ---- reproducibility (Done-when #2) ----

def test_generator_check_mode_passes_on_clean_tree():
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "generator --check failed on committed tree:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


def test_generator_is_deterministic(tmp_path):
    """Regenerating against the same data should yield byte-identical pages."""
    # Snapshot the current page bodies.
    before = {p.name: p.read_bytes() for p in VENUES_DIR.glob("*.md")
              if p.name != "index.md"}
    # Regenerate in place.
    result = subprocess.run(
        [sys.executable, str(GENERATOR)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr
    after = {p.name: p.read_bytes() for p in VENUES_DIR.glob("*.md")
             if p.name != "index.md"}
    assert before == after, "regenerated pages differ from committed versions"


# ---- verificationBadge / evidencePanel contract ----

def test_verification_badge_handles_both_states():
    body = (COMPONENTS_DIR / "verificationBadge.js").read_text(encoding="utf-8")
    # Both branches must exist: verified + awaiting
    assert "Human-verified" in body
    assert "Awaiting human review" in body
    # Pulls reviewer out of human_verification evidence rows
    assert "human_verification" in body


def test_evidence_panel_distinguishes_source_types():
    body = (COMPONENTS_DIR / "evidencePanel.js").read_text(encoding="utf-8")
    for key in (
        "human_verification", "llm_classification", "official_site",
        "oecd_navigator", "iapp_tracker", "unesco_gaigo",
    ):
        assert key in body, key
    # Confidence colour map keys (JS object-literal keys can be bare or quoted)
    for level in ("high", "medium", "low"):
        assert re.search(rf"\b{level}\b\s*:", body), level


def test_evidence_panel_groups_by_field_name():
    body = (COMPONENTS_DIR / "evidencePanel.js").read_text(encoding="utf-8")
    assert "field_name" in body
    assert re.search(r"byField\.set|byField\.get", body)
