#!/usr/bin/env python3
"""Generate sources/coverage_matrix.md from sources/registry.yml + data/agv.csv.

Regenerate with:   python3 scripts/generate_coverage_matrix.py
See CLAUDE.md §5.4 for the deliverable spec.
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = REPO_ROOT / "sources" / "registry.yml"
AGV_CSV_PATH = REPO_ROOT / "data" / "agv.csv"
OUTPUT_PATH = REPO_ROOT / "sources" / "coverage_matrix.md"

# AGVO §3.3 Dimension 1 — canonical order.
ENTITY_TYPES: list[str] = [
    "igo_initiative",
    "intergov_forum",
    "treaty_body",
    "multistakeholder_coalition",
    "industry_consortium",
    "intl_ngo_thinktank",
    "academic_consortium",
    "standards_body_wg",
    "national_regulator_intl",
    "conference_policy_track",
    "standalone_governance_conference",
    "industry_conference",
    "one_off_summit",
]

# AGVO §3.3 Dimension 4 — canonical order.
GEOGRAPHIC_SCOPES: list[str] = [
    "global",
    "transregional",
    "regional",
    "plurilateral",
    "bilateral_plus",
]

VALID_ROLES = {"discovery", "verification", "background"}


def load_registry(path: Path) -> list[dict]:
    with path.open() as fh:
        data = yaml.safe_load(fh)
    sources = data.get("sources", []) if isinstance(data, dict) else []
    for entry in sources:
        role = entry.get("role")
        if role not in VALID_ROLES:
            raise SystemExit(
                f"registry.yml: source '{entry.get('id')}' has invalid role '{role}'"
            )
    return sources


def load_agvs(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(newline="") as fh:
        return list(csv.DictReader(fh))


def count_by_cell(agvs: list[dict]) -> dict[tuple[str, str], int]:
    counts: dict[tuple[str, str], int] = defaultdict(int)
    for row in agvs:
        etype = (row.get("entity_type") or "").strip()
        scope = (row.get("geographic_scope") or "").strip()
        if etype and scope:
            counts[(etype, scope)] += 1
    return counts


def group_sources_by_entity_type(
    sources: list[dict], role: str
) -> dict[str, list[dict]]:
    by_etype: dict[str, list[dict]] = defaultdict(list)
    for s in sources:
        if s.get("role") != role:
            continue
        for etype in s.get("entity_types_covered") or []:
            by_etype[etype].append(s)
    return by_etype


def fmt_source_list(items: list[dict]) -> str:
    if not items:
        return "—"
    return ", ".join(f"`{s['id']}`" for s in items)


def render(sources: list[dict], agvs: list[dict]) -> str:
    discovery_by_et = group_sources_by_entity_type(sources, "discovery")
    verification_by_et = group_sources_by_entity_type(sources, "verification")
    cell_counts = count_by_cell(agvs)

    total_per_etype: dict[str, int] = defaultdict(int)
    for (etype, _scope), n in cell_counts.items():
        total_per_etype[etype] += n

    unknown_etypes = sorted(
        {(row.get("entity_type") or "").strip() for row in agvs}
        - set(ENTITY_TYPES)
        - {""}
    )

    role_counts = {
        role: sum(1 for s in sources if s["role"] == role) for role in VALID_ROLES
    }
    today = datetime.now(UTC).date().isoformat()

    gap_rows: list[str] = []
    missing_verification: list[str] = []

    lines: list[str] = []
    lines.append("# Source Coverage Matrix")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/generate_coverage_matrix.py`. "
        "Do not edit by hand. See CLAUDE.md §5.4."
    )
    lines.append("")
    lines.append(f"- Generated: `{today}`")
    lines.append(f"- Registry: `sources/registry.yml` ({len(sources)} entries)")
    lines.append(
        "- Layer counts: "
        f"discovery={role_counts['discovery']}, "
        f"verification={role_counts['verification']}, "
        f"background={role_counts['background']}"
    )
    lines.append(f"- Data snapshot: `data/agv.csv` ({len(agvs)} AGVs)")
    lines.append("")

    lines.append("## Per entity_type")
    lines.append("")
    lines.append(
        "| entity_type | AGVs | verification sources | discovery sources |"
    )
    lines.append(
        "|---|---:|---|---|"
    )
    for etype in ENTITY_TYPES:
        ver = verification_by_et.get(etype, [])
        dis = discovery_by_et.get(etype, [])
        count = total_per_etype.get(etype, 0)
        if not ver:
            missing_verification.append(etype)
        lines.append(
            f"| `{etype}` | {count} | {fmt_source_list(ver)} | {fmt_source_list(dis)} |"
        )
    lines.append("")

    lines.append("## entity_type × geographic_scope (AGV counts)")
    lines.append("")
    header = "| entity_type | " + " | ".join(f"`{s}`" for s in GEOGRAPHIC_SCOPES) + " | total |"
    sep = "|---|" + "|".join(["---:"] * len(GEOGRAPHIC_SCOPES)) + "|---:|"
    lines.append(header)
    lines.append(sep)
    for etype in ENTITY_TYPES:
        row_cells: list[str] = []
        row_total = 0
        for scope in GEOGRAPHIC_SCOPES:
            n = cell_counts.get((etype, scope), 0)
            row_total += n
            has_verification = bool(verification_by_et.get(etype))
            if n > 0 and not has_verification:
                cell = f"**{n} ⚠**"
                gap_rows.append(
                    f"- `entity_type={etype}` × `geographic_scope={scope}`: "
                    f"{n} AGV(s) but no designated verification source."
                )
            else:
                cell = str(n) if n else "·"
            row_cells.append(cell)
        lines.append(f"| `{etype}` | " + " | ".join(row_cells) + f" | {row_total} |")
    lines.append("")
    lines.append(
        "_`·` = empty cell. `⚠` = AGVs present but no verification source assigned "
        "for this `entity_type` (blocks release per §5.4)._"
    )
    lines.append("")

    lines.append("## Release gate (§5.4)")
    lines.append("")
    if missing_verification:
        lines.append(
            "**FAIL** — the following `entity_type` values have no verification source assigned:"
        )
        lines.append("")
        for etype in missing_verification:
            lines.append(f"- `{etype}`")
        lines.append("")
    else:
        lines.append(
            "**PASS** — every AGVO §3.3 `entity_type` has ≥1 verification source."
        )
        lines.append("")

    if gap_rows:
        lines.append(
            "**FAIL** — cells with AGVs present but no verification source:"
        )
        lines.append("")
        lines.extend(gap_rows)
        lines.append("")
    else:
        lines.append(
            "**PASS** — every populated `(entity_type × geographic_scope)` cell "
            "has a verification source available."
        )
        lines.append("")

    if unknown_etypes:
        lines.append(
            "**WARN** — the following `entity_type` values appear in `data/agv.csv` "
            "but are not listed in AGVO §3.3 Dimension 1:"
        )
        lines.append("")
        for etype in unknown_etypes:
            lines.append(f"- `{etype}`")
        lines.append("")

    lines.append("## Background layer (citation only)")
    lines.append("")
    background = [s for s in sources if s["role"] == "background"]
    if not background:
        lines.append("_None registered._")
    else:
        for s in background:
            lines.append(f"- `{s['id']}` — {s['name']} ({s['url']})")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not REGISTRY_PATH.exists():
        print(f"error: {REGISTRY_PATH} not found", file=sys.stderr)
        return 2
    sources = load_registry(REGISTRY_PATH)
    agvs = load_agvs(AGV_CSV_PATH)
    out = render(sources, agvs)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(out)
    print(
        f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} "
        f"({len(sources)} sources, {len(agvs)} AGVs)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
