#!/usr/bin/env python3
"""Auto-generate per-venue detail pages under ``src/venues/`` from the CSVs
in ``data/`` (CLAUDE.md §9 Task 8).

One ``src/venues/{agv_id}.md`` file is emitted per row in ``data/agv.csv``.
Each page:

  * displays the current name + any former names via the ``name_history`` table;
  * shows the six AGVO classification fields as code badges;
  * renders the prominent verification badge (``verificationBadge`` component);
  * renders a lifecycle transition table;
  * renders the full per-field evidence panel (``evidencePanel`` component);
  * links back to the canonical ``data/agv.csv`` row on GitHub.

**Reproducibility (Task 8 Done-when #2).** Running this script against
unchanged CSVs produces byte-identical output. Inputs are sorted by
``agv_id`` and every interpolation is deterministic.

Usage::

    python3 scripts/generate_venue_pages.py          # regenerate all pages
    python3 scripts/generate_venue_pages.py --check  # CI: fail if stale
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA = REPO_ROOT / "data"
OUT = REPO_ROOT / "src" / "venues"

HEADER_COMMENT = (
    "<!-- Auto-generated by scripts/generate_venue_pages.py — DO NOT EDIT. -->\n"
    "<!-- Regenerate with: python3 scripts/generate_venue_pages.py -->\n"
)

GITHUB_EDIT_BASE = (
    "https://github.com/s00048ri/agv-tracker/edit/main/data/agv.csv"
)


def _esc_yaml(value: str) -> str:
    """Escape a string for use inside a double-quoted YAML scalar."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _esc_md(value: str) -> str:
    """Light Markdown escaping for inline text in a fenced code span."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_page(row: dict) -> str:
    agv_id = row["agv_id"]
    name_en = row.get("name_en", agv_id)
    region = (row.get("region_code") or "").strip()
    scope_val = row.get("geographic_scope", "")
    scope_display = (
        f"`{scope_val}` ({region})" if region else f"`{scope_val}`"
    )
    notes = (row.get("notes") or "").strip()
    last_obs = (row.get("last_observed_activity_date") or "").strip() or "—"
    founded = row.get("founded_date") or "?"
    prec = row.get("founded_date_precision") or "?"
    basis = row.get("establishment_basis") or "?"

    lines: list[str] = []
    lines.append("---")
    lines.append(f'title: "{_esc_yaml(name_en)}"')
    lines.append("toc: true")
    lines.append("---")
    lines.append(HEADER_COMMENT.rstrip())
    lines.append("")
    # Single JS block bundles imports and data loads; Observable Framework
    # runs it once per page render.
    lines.append("```js")
    lines.append(f'const agvId = "{agv_id}";')
    lines.append('const allAgvs = await FileAttachment("../data/agv.json").json();')
    lines.append("const agv = allAgvs.find((r) => r.agv_id === agvId);")
    lines.append(
        'const allEvidence = await FileAttachment("../data/evidence.json").json();'
    )
    lines.append(
        "const evidence = allEvidence.filter((r) => r.agv_id === agvId);"
    )
    lines.append(
        'const allLifecycle = await FileAttachment("../data/lifecycle.json").json();'
    )
    lines.append(
        "const lifecycle = allLifecycle"
    )
    lines.append("  .filter((r) => r.agv_id === agvId)")
    lines.append(
        '  .sort((a, b) => (a.transition_date || "").localeCompare(b.transition_date || ""));'
    )
    lines.append(
        'const allNameHistory = await FileAttachment("../data/name_history.json").json();'
    )
    lines.append(
        "const nameHistory = allNameHistory.filter((r) => r.agv_id === agvId);"
    )
    lines.append(
        'import {verificationBadge} from "../components/verificationBadge.js";'
    )
    lines.append(
        'import {evidencePanel} from "../components/evidencePanel.js";'
    )
    lines.append("```")
    lines.append("")
    lines.append(f"# {name_en}")
    lines.append("")
    lines.append("${verificationBadge(agv, evidence)}")
    lines.append("")
    lines.append("## Classification")
    lines.append("")
    lines.append(f"- **entity_type**: `{row.get('entity_type', '')}`")
    lines.append(
        f"- **governance_modality_primary**: "
        f"`{row.get('governance_modality_primary', '')}`"
    )
    gsec = (row.get("governance_modality_secondary") or "").strip()
    if gsec:
        lines.append(f"- **governance_modality_secondary**: `{gsec}`")
    lines.append(
        f"- **topic_focus_primary**: `{row.get('topic_focus_primary', '')}`"
    )
    for col in ("topic_focus_secondary_1", "topic_focus_secondary_2"):
        v = (row.get(col) or "").strip()
        if v:
            lines.append(f"- **{col}**: `{v}`")
    lines.append(f"- **geographic_scope**: {scope_display}")
    lines.append(
        f"- **lead_actor_primary**: `{row.get('lead_actor_primary', '')}`"
    )
    lsec = (row.get("lead_actor_secondary") or "").strip()
    if lsec:
        lines.append(f"- **lead_actor_secondary**: `{lsec}`")
    lines.append(f"- **legal_character**: `{row.get('legal_character', '')}`")
    lines.append(
        f"- **Founded**: {founded} "
        f"(precision: `{prec}`; basis: `{basis}`)"
    )
    lines.append(f"- **current_state**: `{row.get('current_state', '')}`")
    lines.append(
        f"- **convening_frequency**: `{row.get('convening_frequency', '')}`"
    )
    lines.append(f"- **last_observed_activity_date**: {last_obs}")
    pref_url = row.get("primary_reference_url", "")
    if pref_url:
        lines.append(
            f"- **primary_reference_url**: [{pref_url}]({pref_url})"
        )
    lines.append("")

    # Field-level confidence summary
    lines.append("## Field-level confidence")
    lines.append("")
    lines.append("| Field | Confidence |")
    lines.append("|---|---|")
    for f in (
        "entity_type",
        "founded_date",
        "current_state",
        "legal_character",
    ):
        conf = row.get(f"confidence_{f}") or "?"
        lines.append(f"| `{f}` | `{conf}` |")
    lines.append("")

    # Lifecycle
    lines.append("## Lifecycle timeline")
    lines.append("")
    lines.append("```js")
    lines.append("view(")
    lines.append("  lifecycle.length")
    lines.append("    ? Inputs.table(lifecycle, {")
    lines.append(
        '        columns: ["transition_date", "from_state", "to_state", "notes"],'
    )
    lines.append("        header: {")
    lines.append('          transition_date: "Date",')
    lines.append('          from_state: "From",')
    lines.append('          to_state: "To",')
    lines.append('          notes: "Notes",')
    lines.append("        },")
    lines.append("        format: {")
    lines.append('          from_state: (s) => s || "(initial)",')
    lines.append("        },")
    lines.append("      })")
    lines.append(
        "    : html`<p><em>No lifecycle transitions recorded.</em></p>`"
    )
    lines.append(")")
    lines.append("```")
    lines.append("")

    # Name history
    lines.append("## Name history")
    lines.append("")
    lines.append("```js")
    lines.append("view(")
    lines.append("  nameHistory.length")
    lines.append("    ? Inputs.table(nameHistory, {")
    lines.append(
        '        columns: ["name_type", "name", "valid_from", "valid_to", "source_url"],'
    )
    lines.append("        format: {")
    lines.append('          valid_to: (v) => v || "(current)",')
    lines.append("          source_url: (u) =>")
    lines.append(
        '            u ? htl.html`<a href="${u}" target="_blank" rel="noreferrer">link</a>` : "",'
    )
    lines.append("        },")
    lines.append("      })")
    lines.append("    : html`<p><em>No renamings recorded.</em></p>`")
    lines.append(")")
    lines.append("```")
    lines.append("")

    # Evidence
    lines.append("## Evidence")
    lines.append("")
    lines.append("${evidencePanel(evidence)}")
    lines.append("")

    # Notes + edit link
    lines.append("---")
    lines.append("")
    if notes:
        lines.append(f"*Notes: {_esc_md(notes)}*")
        lines.append("")
    lines.append(f"[Edit this record on GitHub]({GITHUB_EDIT_BASE})")
    lines.append("")
    return "\n".join(lines)


def _load_rows() -> list[dict]:
    with (DATA / "agv.csv").open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return sorted(rows, key=lambda r: r["agv_id"])


def _existing_generated_paths() -> set[Path]:
    return {
        p for p in OUT.glob("*.md")
        if p.name != "index.md"
        and "Auto-generated by scripts/generate_venue_pages.py" in p.read_text(
            encoding="utf-8", errors="ignore"
        )
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Generate per-venue Markdown pages under src/venues/ from data/agv.csv."
        )
    )
    ap.add_argument(
        "--check", action="store_true",
        help="CI mode: write to a temp dir and compare with committed files; "
             "exit 1 if any differ.",
    )
    args = ap.parse_args(argv)

    rows = _load_rows()
    OUT.mkdir(parents=True, exist_ok=True)

    generated_ids: set[str] = set()
    changed: list[str] = []
    for row in rows:
        body = render_page(row)
        target = OUT / f"{row['agv_id']}.md"
        generated_ids.add(row["agv_id"])
        if args.check:
            existing = target.read_text(encoding="utf-8") if target.exists() else ""
            if existing != body:
                changed.append(row["agv_id"])
        else:
            target.write_text(body, encoding="utf-8")

    # Delete orphaned auto-generated files (row removed from agv.csv).
    wanted = {OUT / f"{aid}.md" for aid in generated_ids}
    for orphan in _existing_generated_paths() - wanted:
        if args.check:
            changed.append(f"{orphan.stem} (orphan)")
        else:
            orphan.unlink()

    if args.check:
        if changed:
            print(
                f"check failed: {len(changed)} venue page(s) differ from regeneration: "
                + ", ".join(sorted(changed)[:10])
                + ("…" if len(changed) > 10 else ""),
                file=sys.stderr,
            )
            return 1
        print(f"check ok: {len(rows)} venue pages in sync with data/", file=sys.stderr)
        return 0

    print(f"wrote {len(rows)} venue pages to {OUT.relative_to(REPO_ROOT)}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
